### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmigaTS#2]
Hi,

I would like to build and run some of the tests but there are several cases where `incbin` files seems to be missing. Such as this one https://github.com/dirkwhoffmann/vAmigaTS/blob/master/Blitter/zero/zero0/zero0.s

```
bitplanes:
	incbin	"out/image.bin"
	ds.b    128,$00

emoji:
	incbin	"out/emoji.bin"
	ds.b    128,$00

emojiMask:	
	incbin	"out/emoji-mask.bin"
	ds.b    128,$00
```

Or are the stored at some separate location?

**Comment by dirkwhoffmann** [comment]
Hi Daniel, 

I just uploaded the missing files. They are also missing in other test case directories, but they are always the same three files. Some test cases really need to be cleaned up (especially the older ones). The reason for this is that I never wrote any assembly program on the Amiga back in the day, so the code quality is pretty poor. Since you are a demo coder, you better wear safety goggles before looking at the code in detail 😬. The later tests are a bit better because I learned a lot about programming the Amiga in the last 12 months. 

To build the tests, you should start from here: 
https://github.com/alpine9000/amiga_examples

This is where the test cases originated, and I still use the same tool chain to create them. To test my emulator, I once started running all tests from the above mentioned repo. Once they passed, I started to modify the tests, and this is how the test suite emerged.

**Comment by emoon** [comment]
np :) This repo of tests are awesome :)
